export const BaseURL = 'http://192.168.1.48:8000/'
export const imageURL = 'http://192.168.1.48:8000'
// export const BaseURL = 'https://jetronics.foxiomlabs.com/'
// export const imageURL = 'https://jetronics.foxiomlabs.com'
// export const BaseURL = 'https://server.bioaqua.ae/'
// export const imageURL = 'https://server.bioaqua.ae'